// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: upload.proto

package de.martenl.fashiondan.adserver.upload;

public interface AdUploadReplyOrBuilder extends
        // @@protoc_insertion_point(interface_extends:adupload.AdUploadReply)
        com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string message = 1;</code>
     */
    java.lang.String getMessage();

    /**
     * <code>string message = 1;</code>
     */
    com.google.protobuf.ByteString
    getMessageBytes();
}
