// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: upload.proto

package de.martenl.fashiondan.adserver.upload;

public interface AdUploadRequestOrBuilder extends
        // @@protoc_insertion_point(interface_extends:adupload.AdUploadRequest)
        com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string name = 1;</code>
     */
    java.lang.String getName();

    /**
     * <code>string name = 1;</code>
     */
    com.google.protobuf.ByteString
    getNameBytes();
}
